import './globals.css'
import { ReactNode } from 'react'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'QR Code Generator',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
